# Generated by Django 4.0 on 2022-01-02 16:20

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='books_files'),
        ),
    ]
