# Generated by Django 4.0 on 2021-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylist',
            options={'verbose_name_plural': 'Categories List'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='subcategorylist',
            options={'verbose_name_plural': 'Sub-Categories List'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
